import type {Metadata} from "next";
import {Rubik} from "next/font/google";
import "./globals.css";
import './../styles/styles.scss';
import React from "react";
import Header from "@/widgets/header/Header";
import Footer from "@/widgets/footer/Footer";
import Spacer from "@/shared/Spacer";

const rubik = Rubik({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={(rubik.className)}>
        <Header/>
        <Spacer height={'4px'}/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
