import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import './../styles/main.scss';
import {clsx} from "clsx";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(rubik.className, 'container') }>{children}</body>
    </html>
  );
}
